### PR TITLE
WIP: Remove bintray repository URLs and update dependencies

### PR DESCRIPTION
**Pull request by arian**
I tried to look into #763, but couldn't build the project anymore, because bintray URLs don't work anymore.

```
* What went wrong:
A problem occurred configuring root project 'intellij-elm'.
> Failed to notify project evaluation listener.
   > Could not resolve all files for configuration ':compileOnly'.
      > Could not resolve org.jetbrains.intellij.deps.jflex:jflex:1.7.0-1.
        Required by:
            project :
         > Could not resolve org.jetbrains.intellij.deps.jflex:jflex:1.7.0-1.
            > Could not get resource 'https://dl.bintray.com/kotlin/kotlin-dev/org/jetbrains/intellij/deps/jflex/jflex/1.7.0-1/jflex-1.7.0-1.pom'.
               > Could not HEAD 'https://dl.bintray.com/kotlin/kotlin-dev/org/jetbrains/intellij/deps/jflex/jflex/1.7.0-1/jflex-1.7.0-1.pom'. Received status code 403 from server: Forbidden
         > Could not resolve org.jetbrains.intellij.deps.jflex:jflex:1.7.0-1.
            > Could not get resource 'http://dl.bintray.com/jetbrains/markdown/org/jetbrains/intellij/deps/jflex/jflex/1.7.0-1/jflex-1.7.0-1.pom'.
               > Could not HEAD 'http://dl.bintray.com/jetbrains/markdown/org/jetbrains/intellij/deps/jflex/jflex/1.7.0-1/jflex-1.7.0-1.pom'. Received status code 403 from server: Forbidden
         > Could not resolve org.jetbrains.intellij.deps.jflex:jflex:1.7.0-1.
            > Could not get resource 'https://jetbrains.bintray.com/intellij-third-party-dependencies/org/jetbrains/intellij/deps/jflex/jflex/1.7.0-1/jflex-1.7.0-1.pom'.
               > Could not HEAD 'https://jetbrains.bintray.com/intellij-third-party-dependencies/org/jetbrains/intellij/deps/jflex/jflex/1.7.0-1/jflex-1.7.0-1.pom'. Received status code 403 from server: Forbidden
```

So i tried fixing that:

- Bintray has Sunset
- upgrade grammarkit to 2021.1.3
- upgrade idea gradle plugin to 1.1
- upgrade kotlin to 1.5
- Update gradle to 6.9

That fixes the compile errors, but at the moment i'm still running into:

```
> Task :instrumentCode FAILED
[gradle-intellij-plugin :intellij-elm:instrumentCode] Compiler in 'LATEST-EAP-SNAPSHOT' version can't be resolved from Maven. Minimal version supported: 2018.3+. Use higher 'intellij.version' or specify the 'javac2' property manually.

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':instrumentCode' (type 'IntelliJInstrumentCodeTask').
> No value has been specified for property 'compilerClassPathFromMaven'.
```

It seems things are wrong with the `intellij` configuration, as I can't set the `pluginName` or `updateSinceUntilBuild` properties anymore...

### CODE REVIEW

**Comment by yonigibbs** [comment]
@arian, I notice you upgraded the `org.jetbrains.intellij` plugin from version `0.4.9` to `1.1.4`. On the [GitHub repo for that plugin](https://github.com/JetBrains/gradle-intellij-plugin#the-latest-version-is-114) it says:

> When upgrading to 1.x version, please make sure to follow migration guide to adjust your existing build script: https://lp.jetbrains.com/gradle-intellij-plugin

I had a look at that and noticed the "Restrictive Groovy syntax" section, which shows that you have to use `=` when assigning values to the plugin using Groovy in the new version. So the `intellij` block in `build.gradle` should have this:

```
intellij {
    version = intellijPlatformVersion
    pluginName = 'intellij-elm'
    updateSinceUntilBuild = false
}
```

That seems to get round the problem you mention, but moves onto the next problem (at least on my system):

```
> Task :generateElmParser FAILED
Exception in thread "main" java.lang.NoSuchMethodError: 'com.intellij.openapi.extensions.impl.ExtensionsAreaImpl com.intellij.mock.MockApplication.getExtensionArea()'
        at org.intellij.grammar.LightPsi$Init.initExtensions(LightPsi.java:199)
        at org.intellij.grammar.LightPsi$MyParsing.<init>(LightPsi.java:157)
        at org.intellij.grammar.LightPsi.<clinit>(LightPsi.java:54)
        at org.intellij.grammar.Main.main(Main.java:37)
```

**Comment by yonigibbs** [comment]
And it looks like that last error about generating the Elm parser fails because of a mismatch in some dependencies between the version of GrammarKit and the version of IntelliJ that's used by the build process (I think! - I'm not really that familiar with the GrammarKit side of things). Anyway, it seems that one way around this is to get the build to use a newer version of IntelliJ. For example in `gradle.properties` I changed `intellijPlatformVersion` from `2019.1.2` to `2021.1.2`. Once I did that, the error above was resolved, and the code now compiles.

However... is this the right thing to do? I'm not really sure what the ramifications of this will be. Will it mean, for example, that the plugin might not work on IntelliJ 2019? Also just in general I'm not sure about any other potential dangers of a large-scale upgrade of so many dependencies at once here (Kotlin, IntelliJ, IntelliJ Gradle plugin, GrammarKit, Gradle). There might be hidden side-effects we don't know about.

Anyway, in case you do choose to proceed with this approach... once I made the change above, the next thing to do was in `ElmStubAccessTest` on line 75 where it overrides a function, `processError`, whose signature seems to have changed in the new version of IntelliJ being used. So that just needs a new parameter: `logger: Logger`. With that change made, the tests now compile.

At this point I ran the tests but had 8 failures. I guess because of the change in the IntelliJ version or something like that. So they need to be investigated if you do go with that version of IntelliJ. Maybe an approach with less friction would be to change the version of IntelliJ to not quite the very latest one? Maybe that would be easier.

Hopefully that should help you progress this PR to a state where it builds and all the tests pass. We'll then need to wait for @klazuka to make a call on whether all these upgrades at once are the right approach.

Good luck!

**Comment by arian** [comment]
Thanks for the hint!

With your suggestions I was able to build the plugin indeed, and run the tests. These are the results right now:

```
org.elm.ide.inspections.inference.TypeInferenceInspectionTest3 > test flex arg to rigid param 1 FAILED
    org.junit.ComparisonFailure at TypeInferenceInspectionTest3.kt:976

org.elm.ide.inspections.inference.TypeInferenceInspectionTest3 > test flex arg to rigid param 2 FAILED
    org.junit.ComparisonFailure at TypeInferenceInspectionTest3.kt:986

org.elm.ide.inspections.inference.TypeInferenceInspectionTest1 > test mismatched value type from parametric record alias FAILED
    org.junit.ComparisonFailure at TypeInferenceInspectionTest1.kt:315

org.elm.workspace.ElmWorkspaceServiceTest > test persistence roundtrip FAILED
    com.intellij.serviceContainer.AlreadyDisposedException at ComponentManagerImpl.kt:203

org.elm.workspace.compiler.ElmBuildActionTest > test build Elm application project FAILED
    com.intellij.util.lang.CompoundRuntimeException at RunAll.java:72
        Caused by: com.intellij.serviceContainer.AlreadyDisposedException at ComponentManagerImpl.kt:203

org.elm.workspace.compiler.ElmBuildActionTest > test build Elm application project with an error FAILED
    com.intellij.util.lang.CompoundRuntimeException at RunAll.java:72
        Caused by: com.intellij.serviceContainer.AlreadyDisposedException at ComponentManagerImpl.kt:203

org.elm.workspace.compiler.ElmBuildActionTest > test build Elm project ignores nested function named 'main' FAILED
    com.intellij.util.lang.CompoundRuntimeException at RunAll.java:72
        Caused by: com.intellij.serviceContainer.AlreadyDisposedException at ComponentManagerImpl.kt:203

1394 tests completed, 7 failed
```

Regarding the versions, it'd be nice to keep the version changes as incremental as possible. grammarkit seems to fixed bintray in 2021.1: https://github.com/JetBrains/gradle-grammar-kit-plugin/releases/tag/2021.1, so that would be the lowest version probably to use, but that, I think, needs a compatible `org.jetbrains.intellij` plugin version too.

I don't know what would be the best way to get it building again, so we can update the `until-build` version number?

**Comment by yonigibbs** [comment]
That's great that it helped! So you're now at the same state I got to: 8 or so failing unit tests. I see two options:
1. Find a lower version of IntelliJ that will be compatible with GrammarKit, but hopefully reduce the number of failing tests (hopefully to zero!).
2. Fix the failing tests. The first couple (e.g. `test flex arg to rigid param 1`) actually seem trivial. Looks like the difference is some white space vs `&nbsp;`, so it might be enough simply to update the tests to expect `&nbsp;`, or do some manual cleanup of some data before the comparison. So maybe getting the tests passing won't be too difficult?

**Comment by arian** [comment]
These tests are still failing:

```
org.elm.workspace.compiler.ElmBuildActionTest > test build Elm application project FAILED
    com.intellij.serviceContainer.AlreadyDisposedException at ComponentManagerImpl.kt:187

org.elm.workspace.compiler.ElmBuildActionTest > test build Elm project ignores nested function named 'main' FAILED
    com.intellij.serviceContainer.AlreadyDisposedException at ComponentManagerImpl.kt:187

org.elm.ide.actions.ElmExternalFormatActionTest > test elm-format action with elm 19 FAILED
    com.intellij.serviceContainer.AlreadyDisposedException at ComponentManagerImpl.kt:187

org.elm.ide.actions.ElmExternalFormatActionTest > test elm-format action should add to the undo stack FAILED
    com.intellij.serviceContainer.AlreadyDisposedException at ComponentManagerImpl.kt:187

org.elm.workspace.ElmWorkspaceServiceTest > test persistence roundtrip FAILED
    com.intellij.serviceContainer.AlreadyDisposedException at ComponentManagerImpl.kt:187

1394 tests completed, 5 failed
```

I think this has to do with how the `elm` or `elm-format` binaries are executed. For example, when I use the `runIde` gradle task, and compile an elm file through the UI, I get:

```
2021-08-14 13:00:54,498 [  96028]  ERROR -      #com.intellij.util.ui.EDT - Assert: must be called on EDT 
java.lang.Throwable: Assert: must be called on EDT
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.util.ui.EDT.assertIsEdt(EDT.java:64)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.show(ToolWindowImpl.kt:234)
	at org.elm.workspace.compiler.ElmBuildAction.actionPerformed$make(ElmBuildAction.kt:105)
	at org.elm.workspace.compiler.ElmBuildAction.access$actionPerformed$make(ElmBuildAction.kt:37)
	at org.elm.workspace.compiler.ElmBuildAction$actionPerformed$makeTask$1.run(ElmBuildAction.kt:113)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:450)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:117)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:510)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:243)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:243)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-08-14 13:00:54,501 [  96031]  ERROR -      #com.intellij.util.ui.EDT - IntelliJ IDEA 2021.2  Build #IC-212.4746.92 
2021-08-14 13:00:54,505 [  96035]  ERROR -      #com.intellij.util.ui.EDT - JDK: 11.0.11; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2021-08-14 13:00:54,505 [  96035]  ERROR -      #com.intellij.util.ui.EDT - OS: Linux 
2021-08-14 13:00:54,506 [  96036]  ERROR -      #com.intellij.util.ui.EDT - Plugin to blame: Elm version: 4.4.0 
2021-08-14 13:00:54,506 [  96036]  ERROR -      #com.intellij.util.ui.EDT - Last Action: Elm.Build 
2021-08-14 13:00:54,509 [  96039]  ERROR -      #com.intellij.util.ui.EDT - Assert: must be called on EDT 
java.lang.Throwable: Assert: must be called on EDT
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.util.ui.EDT.assertIsEdt(EDT.java:64)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindow(ToolWindowManagerImpl.kt:837)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.show(ToolWindowImpl.kt:235)
	at org.elm.workspace.compiler.ElmBuildAction.actionPerformed$make(ElmBuildAction.kt:105)
	at org.elm.workspace.compiler.ElmBuildAction.access$actionPerformed$make(ElmBuildAction.kt:37)
	at org.elm.workspace.compiler.ElmBuildAction$actionPerformed$makeTask$1.run(ElmBuildAction.kt:113)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:450)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:117)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:510)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:243)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:243)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-08-14 13:00:54,512 [  96042]  ERROR -      #com.intellij.util.ui.EDT - IntelliJ IDEA 2021.2  Build #IC-212.4746.92 
2021-08-14 13:00:54,512 [  96042]  ERROR -      #com.intellij.util.ui.EDT - JDK: 11.0.11; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2021-08-14 13:00:54,513 [  96043]  ERROR -      #com.intellij.util.ui.EDT - OS: Linux 
2021-08-14 13:00:54,513 [  96043]  ERROR -      #com.intellij.util.ui.EDT - Plugin to blame: Elm version: 4.4.0 
2021-08-14 13:00:54,513 [  96043]  ERROR -      #com.intellij.util.ui.EDT - Last Action: Elm.Build 
```

I'm going to look into how the plugin runs those binaries now, and see if there there's an advised way in the intellij documentation.

**Comment by arian** [comment]
Ok, the last commits I added do fix the tests, but, as it comments out some lines, can't be the correct fixes yet.

**Comment by arian** [comment]
Running elm / elm-format binaries still throws some errors. But they do work.

```
2021-08-14 16:08:37,809 [ 296532]  ERROR - ution.process.OSProcessHandler - Synchronous execution on EDT: /home/arian/.local/bin/elm-format --yes --elm-version=0.19 --stdin, see com.intellij.execution.process.OSProcessHandler#checkEdtAndReadAction() Javadoc for resolutions 
java.lang.Throwable: Synchronous execution on EDT: /home/arian/.local/bin/elm-format --yes --elm-version=0.19 --stdin, see com.intellij.execution.process.OSProcessHandler#checkEdtAndReadAction() Javadoc for resolutions
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.execution.process.OSProcessHandler.checkEdtAndReadAction(OSProcessHandler.java:172)
	at com.intellij.execution.process.OSProcessHandler.waitFor(OSProcessHandler.java:117)
	at com.intellij.execution.process.CapturingProcessRunner.runProcess(CapturingProcessRunner.java:61)
	at com.intellij.execution.process.CapturingProcessHandler.runProcess(CapturingProcessHandler.java:72)
	at org.elm.openapiext.SubprocessesKt.execute(Subprocesses.kt:113)
	at org.elm.openapiext.SubprocessesKt.execute$default(Subprocesses.kt:92)
	at org.elm.workspace.commandLineTools.ElmFormatCLI.getFormattedContentOfDocument(ElmFormatCLI.kt:41)
	at org.elm.workspace.commandLineTools.ElmFormatCLI.formatDocumentAndSetText$lambda-0(ElmFormatCLI.kt:55)
	at com.intellij.openapi.progress.impl.CoreProgressManager$1.run(CoreProgressManager.java:279)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:450)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:117)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$8(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:407)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:567)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:88)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:275)
	at org.elm.workspace.commandLineTools.ElmFormatCLI.formatDocumentAndSetText(ElmFormatCLI.kt:54)
	at org.elm.ide.components.ElmFormatOnFileSaveComponent$initComponent$1.beforeDocumentSaving(ElmFormatOnFileSaveComponent.kt:40)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:645)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:620)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:417)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:390)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:179)
	at com.sun.proxy.$Proxy8.beforeDocumentSaving(Unknown Source)
```

**Comment by totof99** [comment]
For people wanting to compile the old version of the plugin, there is no need to modify everything. You can easily compile manually the missing thirdparties.
First, you need to change build.gradle to use org.jetbrains.grammarkit as a plugin instead of a classpath dependencies. It will enable retrieving from local maven repo.

Just clone the git repository for jflex, checkout the correct version tag, and publish to local maven repo using "mvn clean install"
https://github.com/JetBrains/intellij-deps-jflex/tree/1.7.0-1
I used an old JDK14 to compile without issue.

**Comment by cies** [comment]
Changes proposed by this PR have largely been caught up with in `master`. I'm closing it.
